kind: Service
apiVersion: v1
metadata:
  name: service-b
  labels:
    app: service-b
    visualize: "true"
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: http
  selector:
    app: service-b
    serving: "true"
